# Generated by Django 2.1.5 on 2021-01-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
