# Generated by Django 2.1.5 on 2021-01-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../../static/course/images/default-avatar.jpg', upload_to='../../static/course/images'),
        ),
    ]
