# Generated by Django 2.1.5 on 2021-01-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210103_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_class',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
