# Generated by Django 2.1.5 on 2021-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20210104_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='static/course/images/'),
        ),
    ]
