# Generated by Django 2.1.5 on 2021-01-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20210104_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='media/course/images/'),
        ),
    ]
