# Generated by Django 2.1.5 on 2021-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20210312_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
