# Generated by Django 2.1.5 on 2021-05-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20210522_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Class'),
            preserve_default=False,
        ),
    ]
