# Generated by Django 2.1.5 on 2021-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_questions_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_class',
            name='code',
        ),
        migrations.AddField(
            model_name='student_class',
            name='asked_ques',
            field=models.IntegerField(default=0),
        ),
    ]
