# Generated by Django 2.1.5 on 2021-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_auto_20210527_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='marks',
            field=models.FloatField(default=-1),
        ),
    ]
