# Generated by Django 2.1.5 on 2021-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_voteforanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='answers',
            name='vote',
            field=models.FloatField(default=0.0),
        ),
    ]
