# Generated by Django 2.1.5 on 2021-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_auto_20210615_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
