# Generated by Django 2.1.5 on 2021-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_short_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_answered_by',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
